"""Generate install-links.json for DevinoSolutions/mcp-servers.

Sources:
  - <server>/mcp.json                     -> server name + MCP endpoint
  - .cursor-plugin/marketplace.json       -> display names (plugins[].name order)
  - README.md server table                -> the exact Cursor / VS Code / Replit / Kiro
                                             one-click links already published (kept byte-for-byte,
                                             same encodings gen_links.py produced)

Usage: python gen_install_links.py [repo_root]
"""
import base64
import json
import re
import sys
from pathlib import Path
from urllib.parse import quote

ROOT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parents[1]
REPO = "https://github.com/DevinoSolutions/mcp-servers"

readme = (ROOT / "README.md").read_text(encoding="utf-8")

# One README table row per server: | <img> | [Display](dir) | desc | `endpoint` | one-click links |
row_re = re.compile(
    r"^\|\s*<img[^\n]*\|\s*\[([^\]]+)\]\(([^)]*)\)\s*\|[^\n]*\|\s*`([^`]+)`\s*\|\s*([^\n]+?)\s*\|\s*$",
    re.M,
)
link_re = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")

readme_rows = {}
for m in row_re.finditer(readme):
    display, folder, endpoint, oneclick = m.groups()
    links = {label: url for label, url in link_re.findall(oneclick)}
    readme_rows[folder] = {"display": display, "endpoint": endpoint, "links": links}

marketplace = json.loads((ROOT / ".cursor-plugin" / "marketplace.json").read_text(encoding="utf-8"))
plugins = marketplace["plugins"]


def b64(obj) -> str:
    raw = json.dumps(obj, separators=(",", ":")).encode()
    return base64.b64encode(raw).decode()


def cursor_deeplink(name, url):
    # cursor://anysphere.cursor-deeplink/mcp/install?name=<name>&config=<base64 {"url":...}>
    return f"cursor://anysphere.cursor-deeplink/mcp/install?name={quote(name, safe='')}&config={b64({'url': url})}"


def vscode_deeplink(name, url):
    # vscode:mcp/install?<urlencoded {"name":...,"type":"http","url":...}>
    cfg = json.dumps({"name": name, "type": "http", "url": url}, separators=(",", ":"))
    return f"vscode:mcp/install?{quote(cfg, safe='')}"


entries = []
for p in plugins:
    name = p["name"]
    folder = p["source"]
    mcp = json.loads((ROOT / folder / "mcp.json").read_text(encoding="utf-8"))["mcpServers"]
    if list(mcp.keys()) != [name]:
        sys.exit(f"{folder}/mcp.json server key {list(mcp)} != plugin name {name}")
    mcp_url = mcp[name]["url"]

    row = readme_rows.get(folder)
    if row is None:
        sys.exit(f"README has no table row for {folder}")
    if row["endpoint"] != mcp_url:
        sys.exit(f"README endpoint for {folder} ({row['endpoint']}) != mcp.json ({mcp_url})")
    display = row["display"]
    for label in ("Cursor", "VS Code", "Replit", "Kiro"):
        if label not in row["links"]:
            sys.exit(f"README row for {folder} has no {label} link")

    entries.append(
        {
            "name": name,
            "displayName": display,
            "description": p["description"],
            "mcpUrl": mcp_url,
            "docs": f"{REPO}/tree/main/{folder}",
            "homepage": p.get("homepage"),
            "links": {
                "cursor": row["links"]["Cursor"],
                "cursorDeeplink": cursor_deeplink(name, mcp_url),
                "vscode": row["links"]["VS Code"],
                "vscodeDeeplink": vscode_deeplink(name, mcp_url),
                "kiro": row["links"]["Kiro"],
                "replit": row["links"]["Replit"],
                "claudeDirectory": {"url": f"https://claude.ai/directory/{name}", "verified": False},
                "chatgpt": None,
                "antigravityCommand": f"agy plugin install {REPO}/antigravity-plugins/{name}",
                "geminiCliCommand": f"gemini extensions install {REPO}",
                "claudeCodeCommand": f"claude mcp add --transport http {name} {mcp_url}",
                "codexToml": f'[mcp_servers.{name}]\nurl = "{mcp_url}"\n',
                "manualUrl": mcp_url,
            },
        }
    )

if len(entries) != 14:
    sys.exit(f"expected 14 servers, built {len(entries)}")

out = {
    "$comment": "Generated by gen_install_links.py from <server>/mcp.json, .cursor-plugin/marketplace.json and the README table. Edit those sources, not this file.",
    "repository": REPO,
    "badges": f"https://cdn.jsdelivr.net/gh/DevinoSolutions/mcp-servers@main/badges/",
    "servers": entries,
}
(ROOT / "install-links.json").write_text(json.dumps(out, indent=2) + "\n", encoding="utf-8", newline="\n")
print("wrote install-links.json with", len(entries), "servers")
